# Streamlit Secrets Template
# Copy this file to secrets.toml and fill in your actual values

[default]
DISCORD_BOT_TOKEN = "YOUR_DISCORD_BOT_TOKEN_HERE"
DISCORD_GUILD_ID = "1393935478503243917"

# Instructions for Streamlit Cloud:
# 1. Go to your app settings in Streamlit Cloud
# 2. Navigate to "Secrets" section
# 3. Add these secrets:
#    DISCORD_BOT_TOKEN = "your_actual_token"
#    DISCORD_GUILD_ID = "1393935478503243917" 